version: 2
jobs:
  build:
    working_directory: ~/code-gov
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Add Node Module's bin to PATH
          command: echo "export PATH=`pwd`/node_modules/.bin:$PATH" >> $BASH_ENV
      - restore_cache:
          key: code-gov-api-client-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: code-gov-api-client-{{ checksum "package.json" }}
          paths:
            - code-gov-api-client/node_modules
      - run:
          name: Run Linter
          command: npm run lint
  test:
    working_directory: ~/code-gov
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: code-gov-api-client-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: code-gov-api-client-{{ checksum "package.json" }}
          paths:
            - code-gov-api-client/node_modules
      - run:
          name: Run Tests
          command: npm test
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
