version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.12.2-stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
  lint:
    docker:
      - image: circleci/node:6.12.2-stretch
    steps:
      - checkout
      - run:
          name: Check Syntax
          command: npm run lint
  test:
    docker:
      - image: circleci/node:6.12.2-stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires: 
            - build
            - lint
